### ISSUE TITLE
Video tags are not selectable

### ISSUE THREAD

**Issue by square360-steven** [rosszurowski/fitvids#7]
I use the <video> tag but there is no default styling for that tag.

Thank you

**Comment by rosszurowski** [comment]
Video tags aren't included because they're responsive by default, like images. If you're using `<video>` tags, you don't need fitvids to make them responsive, you only need the same big of CSS to make `<img>` tags responsive.

```css
img,
video {
  max-width: 100%;
  height: auto;
}
```

(See it [in action here](https://jsfiddle.net/bed79aqz/))

Hope this helps.
